sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rajeshtalla0209/docker-react -f Dockerfile .

script:
  - docker run -e CI=true rajeshtalla0209/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-892439276670"
  bucket_path: "docker"
  on:
   branch: main
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key : $AWS_SECRET_KEY
